-- ==============================================================================
-- AQUASCAPE LEGENDARY FISH — ultra-rare, DB-persisted (run in Supabase SQL Editor)
-- Safe to re-run.
-- ==============================================================================

-- Mark each communal fish as rolled-once so odds stay ~1% across many callers.
alter table public.communal_fishes
  add column if not exists legendary_rolled boolean not null default false;

-- Permanent record of legendary winners.
create table if not exists public.legendary_fish (
  id         bigint generated by default as identity primary key,
  name       text not null,
  species    text,
  entry_date date not null default current_date,
  won_at     timestamptz not null default now()
);

create index if not exists idx_legendary_fish_entry_date
  on public.legendary_fish (entry_date desc);

alter table public.legendary_fish enable row level security;

drop policy if exists "Allow public read access" on public.legendary_fish;
create policy "Allow public read access"
  on public.legendary_fish for select using (true);
-- No public insert/update/delete: writes happen only via the SECURITY DEFINER RPC.

-- Ultra-rare, idempotent, atomic roll. Returns true if this call won.
create or replace function public.roll_legendary(p_name text)
returns boolean
language plpgsql security definer as $$
declare
  v_name text := btrim(regexp_replace(coalesce(p_name,''), '\s+', ' ', 'g'));
  v_row  public.communal_fishes;
  v_win  boolean := false;
begin
  if char_length(v_name) < 1 then return false; end if;

  select * into v_row
  from public.communal_fishes
  where btrim(regexp_replace(name,'\s+',' ','g')) = v_name
    and entry_date = current_date
    and legendary_rolled = false
  order by created_at desc
  limit 1
  for update skip locked;

  if not found then
    return false; -- already rolled (idempotent) or no eligible row today
  end if;

  update public.communal_fishes set legendary_rolled = true where id = v_row.id;

  if random() < 0.01 then
    v_win := true;
    insert into public.legendary_fish (name, species, entry_date)
    values (v_name, v_row.species, current_date);
  end if;

  return v_win;
end;
$$;

grant execute on function public.roll_legendary(text) to anon;

-- Live updates so all clients see a new legend without refresh.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'legendary_fish'
  ) then
    alter publication supabase_realtime add table public.legendary_fish;
  end if;
end $$;
