-- ==============================================================================
-- AQUASCAPE COMMUNAL LIVE TANK - SUPABASE SCHEMA & SETUP
-- ==============================================================================
-- Jalankan skrip ini di Supabase Dashboard -> SQL Editor

-- 1. Buat tabel communal_fishes untuk menerima nama ikan harian (Webhook / Form)
create table if not exists public.communal_fishes (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  species text default 'neonTetra',
  created_at timestamp with time zone default now() not null,
  entry_date date default current_date not null
);

-- Keterangan Kolom:
-- - name: Nama ikan yang akan ditampilkan pada nametag
-- - species: Jenis ikan (default otomatis ke 'neonTetra')
-- - created_at: Timestamp waktu kirim (default now())
-- - entry_date: Tanggal kirim untuk filter hari ini (default current_date)

-- 2. Buat index agar query filter hari ini (current day) berkecepatan tinggi
create index if not exists idx_communal_fishes_created_at
  on public.communal_fishes (created_at desc);

create index if not exists idx_communal_fishes_entry_date
  on public.communal_fishes (entry_date desc);

-- 3. Aktifkan Row Level Security (RLS) & Berikan Izin Akses
alter table public.communal_fishes enable row level security;

-- Izinkan publik (Anon Key) membaca data ikan hari ini
create policy "Allow public read access"
  on public.communal_fishes
  for select
  using (true);

-- Izinkan webhook / aplikasi luar (Anon Key / Service Key) menambahkan nama ikan baru
-- Validasi: nama wajib 1-100 karakter (setelah trim). Hanya INSERT yang dibuka;
-- tidak ada UPDATE/DELETE publik, jadi anon tidak bisa mengubah/menghapus data.
drop policy if exists "Allow public insert access" on public.communal_fishes;
create policy "Allow public insert access"
  on public.communal_fishes
  for insert
  with check (char_length(btrim(name)) between 1 and 100);

-- 4. Aktifkan Supabase Realtime untuk tabel ini (Live WebSocket spawn di browser)
alter publication supabase_realtime add table public.communal_fishes;

-- 5. Contoh data uji coba untuk hari ini
insert into public.communal_fishes (name, species)
values
  ('Bintang Samudra', 'neonTetra'),
  ('Lentera Senja', 'neonTetra'),
  ('Pahlawan Laut', 'orca')
on conflict do nothing;
