import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { Header } from './components/Header';
import { Hero } from './components/Hero';
import { ProjectCard } from './components/ProjectCard';
import { ReadmeModal } from './components/ReadmeModal';
import { ZenAquariumModal } from './components/ZenAquariumModal';
import { reposData } from './data/reposData';
import { RepoItem, AquascapeSettings } from './types';
import { aquascapeAudio } from './components/AquascapeAudio';
import { Search, FolderGit2, Compass, Maximize2, Filter } from 'lucide-react';

export default function App() {
  const [data, setData] = useState(reposData);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedLanguage, setSelectedLanguage] = useState<string>('all');
  const [activeReadmeRepo, setActiveReadmeRepo] = useState<RepoItem | null>(null);

  // Fetch real-time repos.json generated by automated workflow
  useEffect(() => {
    fetch('./repos.json')
      .then((res) => (res.ok ? res.json() : null))
      .then((json) => {
        if (json && Array.isArray(json.repos)) {
          setData(json);
        }
      })
      .catch((err) => {
        console.log('Using bundled reposData:', err);
      });
  }, []);

  // Aquascape simulation settings state
  const [settings, setSettings] = useState<AquascapeSettings>({
    lighting: 'daylight',
    co2Active: true,
    waterFlow: 'normal',
    soundEnabled: false,
    zenMode: false,
    showFlora: true,
    fishDensity: 12,
    activeSpecies: ['mascot', 'neonTetra', 'cherryShrimp', 'angelfish', 'rasbora', 'guppy'],
    showNametags: false,
  });

  const handleUpdateSettings = useCallback((newSettings: Partial<AquascapeSettings>) => {
    setSettings((prev) => ({ ...prev, ...newSettings }));
  }, []);

  const handleToggleSound = useCallback(() => {
    const isNowPlaying = aquascapeAudio.toggle();
    setSettings((prev) => ({ ...prev, soundEnabled: isNowPlaying }));
  }, []);

  const handleFeedFish = useCallback(() => {
    if (typeof (window as unknown as { __aquascapeDropFood?: () => void }).__aquascapeDropFood === 'function') {
      (window as unknown as { __aquascapeDropFood?: () => void }).__aquascapeDropFood?.();
    }
  }, []);

  // Compute all available languages and their counts
  const languageCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    data.repos.forEach((repo) => {
      if (repo.language) {
        counts[repo.language] = (counts[repo.language] || 0) + 1;
      }
    });
    return counts;
  }, [data.repos]);

  // Filtered repositories based on search and language filter
  const filteredRepos = useMemo(() => {
    const query = searchQuery.trim().toLowerCase();
    return data.repos.filter((repo) => {
      const matchesLang =
        selectedLanguage === 'all' || repo.language === selectedLanguage;
      const matchesSearch =
        !query ||
        repo.name.toLowerCase().includes(query) ||
        repo.description.toLowerCase().includes(query) ||
        (repo.topics && repo.topics.some((t) => t.toLowerCase().includes(query)));
      return matchesLang && matchesSearch;
    });
  }, [data.repos, searchQuery, selectedLanguage]);

  return (
    <div className="min-h-screen bg-[#070b12] text-[#e2e8f0] flex flex-col selection:bg-teal-500/30 selection:text-teal-200">
      {/* 1. Header */}
      <Header
        soundEnabled={settings.soundEnabled}
        onToggleSound={handleToggleSound}
        zenMode={settings.zenMode}
        onToggleZen={() => handleUpdateSettings({ zenMode: !settings.zenMode })}
      />

      {/* 2. Hero Section with Interactive Aquascape Tank */}
      <Hero
        data={data}
        settings={settings}
        onUpdateSettings={handleUpdateSettings}
        onFeedFish={handleFeedFish}
      />

      {/* 3. Main Projects Catalog & Explorer */}
      <main id="projects" className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Sticky Filter & Search Toolbar */}
        <div className="sticky top-20 z-30 mb-8 p-3 sm:p-4 rounded-2xl bg-[#0a121d]/90 backdrop-blur-xl border border-teal-500/20 shadow-xl shadow-black/40">
          <div className="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4">
            {/* Search Input */}
            <div className="relative flex-1">
              <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
              <input
                type="text"
                id="search-input"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Cari repositori, kata kunci, topik, atau fitur..."
                className="w-full pl-10 pr-4 py-2.5 rounded-xl bg-slate-900/80 border border-slate-700/60 focus:border-teal-400/60 focus:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-teal-400/20 text-sm text-white placeholder:text-slate-500 transition-all"
                aria-label="Cari proyek"
              />
              {searchQuery && (
                <button
                  type="button"
                  onClick={() => setSearchQuery('')}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-mono text-slate-400 hover:text-white"
                >
                  Clear
                </button>
              )}
            </div>

            {/* Language Filter Chips */}
            <div className="flex items-center gap-2 overflow-x-auto pb-1 md:pb-0 scrollbar-none">
              <span className="text-xs font-semibold text-slate-400 flex items-center gap-1 shrink-0 ml-1">
                <Filter className="w-3.5 h-3.5 text-teal-400" />
                <span>Bahasa:</span>
              </span>

              <button
                type="button"
                onClick={() => setSelectedLanguage('all')}
                className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer shrink-0 ${
                  selectedLanguage === 'all'
                    ? 'bg-teal-500 text-slate-950 shadow-md shadow-teal-500/20 font-bold'
                    : 'bg-slate-900/80 border border-slate-700/60 text-slate-300 hover:text-white hover:border-slate-600'
                }`}
              >
                Semua ({data.repos.length})
              </button>

              {Object.entries(languageCounts).map(([lang, count]) => (
                <button
                  key={lang}
                  type="button"
                  onClick={() => setSelectedLanguage(lang)}
                  className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer shrink-0 ${
                    selectedLanguage === lang
                      ? 'bg-teal-500 text-slate-950 shadow-md shadow-teal-500/20 font-bold'
                      : 'bg-slate-900/80 border border-slate-700/60 text-slate-300 hover:text-white hover:border-slate-600'
                  }`}
                >
                  {lang} ({count})
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Results Counter & Info */}
        <div className="flex items-center justify-between mb-6 text-sm text-slate-400">
          <div className="flex items-center gap-2 font-mono text-xs sm:text-sm">
            <span>
              Menampilkan <strong className="text-teal-300 font-bold">{filteredRepos.length}</strong> dari {data.repos.length} proyek
            </span>
            {selectedLanguage !== 'all' && (
              <span className="text-xs px-2 py-0.5 rounded-md bg-teal-950/60 border border-teal-500/30 text-teal-300">
                filter: {selectedLanguage}
              </span>
            )}
          </div>

          <span className="text-xs text-slate-500 hidden sm:inline">
            Klik kartu untuk membaca dokumentasi README
          </span>
        </div>

        {/* Projects Grid */}
        {filteredRepos.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredRepos.map((repo, idx) => (
              <ProjectCard
                key={repo.name}
                repo={repo}
                index={idx}
                onOpenReadme={(selectedRepo) => setActiveReadmeRepo(selectedRepo)}
              />
            ))}
          </div>
        ) : (
          /* Empty Search State */
          <div className="text-center py-20 px-4 rounded-2xl bg-slate-900/30 border border-slate-800">
            <FolderGit2 className="w-12 h-12 text-slate-600 mx-auto mb-4" />
            <h4 className="text-lg font-bold text-white mb-1">
              Tidak ada repositori yang cocok
            </h4>
            <p className="text-sm text-slate-400 max-w-md mx-auto mb-6">
              Tidak ditemukan proyek dengan kata kunci &quot;{searchQuery}&quot;. Coba ganti kata pencarian atau pilih filter bahasa yang lain.
            </p>
            <button
              type="button"
              onClick={() => {
                setSearchQuery('');
                setSelectedLanguage('all');
              }}
              className="px-4 py-2 text-xs font-bold rounded-xl bg-teal-500/20 border border-teal-500/40 text-teal-200 hover:bg-teal-500 hover:text-slate-950 transition-all cursor-pointer"
            >
              Reset Filter & Pencarian
            </button>
          </div>
        )}

        {/* Aquascape Philosophy & Interactive Highlight Banner */}
        <div className="mt-16 p-6 sm:p-8 rounded-3xl bg-slate-900/90 border border-teal-500/20 backdrop-blur-md relative overflow-hidden shadow-xl shadow-black/40">
          <div className="relative z-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
            <div className="max-w-2xl">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-teal-500/15 border border-teal-400/25 text-teal-300 text-xs font-semibold uppercase tracking-wider mb-3">
                <Compass className="w-3.5 h-3.5 text-teal-300" />
                <span>Filosofi Desain & Ekosistem</span>
              </div>
              <h4 className="text-xl sm:text-2xl font-bold text-white tracking-tight mb-2 font-sans">
                Seperti Seni Menata Aquascape
              </h4>
              <p className="text-sm text-slate-300 leading-relaxed">
                Aquascape bukan sekadar akuarium berisi air, melainkan karya seni ekosistem seimbang antara tanaman, bebatuan, kayu, dan fauna yang saling menghidupkan. Begitu pula kode dan repositori kami di <strong>AQUASCAPE.org</strong>: dibangun dengan struktur yang teratur, deterministik, dan harmonis.
              </p>
            </div>

            <button
              type="button"
              onClick={() => handleUpdateSettings({ zenMode: true })}
              className="shrink-0 flex items-center gap-2 px-5 py-3 rounded-2xl bg-teal-500 hover:bg-teal-400 text-slate-950 font-bold text-sm transition-all shadow-lg shadow-teal-500/20 active:scale-95 cursor-pointer"
            >
              <Maximize2 className="w-4 h-4" />
              <span>Buka Aquarium Layar Penuh</span>
            </button>
          </div>
        </div>
      </main>

      {/* 4. README Modal Viewer */}
      <ReadmeModal
        repo={activeReadmeRepo}
        onClose={() => setActiveReadmeRepo(null)}
      />

      {/* 5. Zen Fullscreen Aquarium Modal */}
      <ZenAquariumModal
        isOpen={settings.zenMode}
        onClose={() => handleUpdateSettings({ zenMode: false })}
        settings={settings}
        onUpdateSettings={handleUpdateSettings}
        onFeedFish={handleFeedFish}
      />

      {/* 6. Footer */}
      <footer className="border-t border-slate-800/80 bg-[#05080e] py-8 text-center text-xs text-slate-400">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <span className="font-bold text-slate-200">AQUASCAPE</span>
            <span>&bull;</span>
            <span>Open Source & Engineering Organization</span>
          </div>

          <div className="flex items-center gap-6">
            <a
              href="https://github.com/aquascapedotorg"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-teal-300 transition-colors"
            >
              GitHub Organization
            </a>
            <a href="#projects" className="hover:text-teal-300 transition-colors">
              Proyek
            </a>
            <button
              type="button"
              onClick={handleToggleSound}
              className="hover:text-teal-300 transition-colors cursor-pointer"
            >
              {settings.soundEnabled ? 'Matikan Suara' : 'Bunyikan Air'}
            </button>
          </div>
        </div>

        <div className="max-w-7xl mx-auto px-4 mt-4 text-[11px] text-slate-500">
          Data terakhir diperbarui:{' '}
          {new Date(data.generated_at).toLocaleDateString('id-ID', {
            day: 'numeric',
            month: 'long',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
          })}
        </div>
      </footer>
    </div>
  );
}
